server:
  port: 8089
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    keyStoreType: PKCS12
    keyAlias: tomcat

spring:
  application:
    name: mcl
  profiles:
    active: dev