INSERT INTO `t_form` VALUES ('1', '环境&形象保养追踪表', '1', '0');
INSERT INTO `t_form` VALUES ('2', '周店面运营评估表', '1', '0');
INSERT INTO `t_form` VALUES ('3', '日环境工作检查表（照片）', '2', '0');
INSERT INTO `t_form` VALUES ('4', '开铺打烊记录表', '1', '0');

INSERT INTO `t_form_item` VALUES ('1', '1', '店外', '1', '0');
INSERT INTO `t_form_item` VALUES ('2', '1', '店外服务功能牌', '2', '1');
INSERT INTO `t_form_item` VALUES ('3', '1', '店外指路牌(固定)清洁无积垢灰尘', '3', '1');
INSERT INTO `t_form_item` VALUES ('4', '1', '门头驰加招牌', '4', '1');
INSERT INTO `t_form_item` VALUES ('5', '1', '外挂品牌灯箱', '5', '1');
INSERT INTO `t_form_item` VALUES ('6', '1', '米其林先生卷帘门', '6', '1');
INSERT INTO `t_form_item` VALUES ('7', '1', '接待区', '7', '0');
INSERT INTO `t_form_item` VALUES ('8', '1', '店内消防栓、灭火器、灭火器箱清洁且未过保质期', '8', '1');
INSERT INTO `t_form_item` VALUES ('9', '1', '空调设备出回风口及空调滤网清洁', '9', '1');
INSERT INTO `t_form_item` VALUES ('10', '1', '玻璃幕墙干净清洁无污渍', '10', '1');
INSERT INTO `t_form_item` VALUES ('11', '1', '工位区', '11', '0');
INSERT INTO `t_form_item` VALUES ('12', '1', '美容工位洗衣机清洁除垢', '12', '1');
INSERT INTO `t_form_item` VALUES ('13', '1', '操作区消防栓\\灭火器清洁完好', '13', '1');
INSERT INTO `t_form_item` VALUES ('14', '1', '车间驰加标准操作海报清洁完好', '14', '1');
INSERT INTO `t_form_item` VALUES ('15', '1', '车间所有设备黄线清晰完整', '15', '1');
INSERT INTO `t_form_item` VALUES ('16', '1', '操作区工位牌、禁止吸烟牌等指示牌清洁无污垢', '16', '1');
INSERT INTO `t_form_item` VALUES ('17', '1', '库房', '17', '0');
INSERT INTO `t_form_item` VALUES ('18', '1', '轮胎及配件摆放整齐且标签向外且清洁无积灰', '18', '1');
INSERT INTO `t_form_item` VALUES ('19', '1', '废弃旧件及轮胎整体存放并及时清理', '19', '1');
INSERT INTO `t_form_item` VALUES ('20', '1', '消防栓灭火器完好/位置正确', '20', '1');
INSERT INTO `t_form_item` VALUES ('21', '2', '环境', '1', '0');
INSERT INTO `t_form_item` VALUES ('22', '2', '室外5米范围内，无任何垃圾(烟头、纸屑、生活垃圾、杂物)，车辆停放有序，工具摆放整齐', '2', '1');
INSERT INTO `t_form_item` VALUES ('23', '2', '陈列商品明码实价，货架及商品上无灰尘', '3', '1');
INSERT INTO `t_form_item` VALUES ('24', '2', '平衡机上的平衡块堆放整齐', '4', '1');
INSERT INTO `t_form_item` VALUES ('25', '2', '设备保养贴符合要求，上墙工具在无施工时无遗漏', '5', '1');
INSERT INTO `t_form_item` VALUES ('26', '2', '举升机的坑道下无垃圾', '6', '1');
INSERT INTO `t_form_item` VALUES ('27', '2', '陈列设备上无油渍和污渍', '7', '1');
INSERT INTO `t_form_item` VALUES ('28', '2', '人员', '8', '0');
INSERT INTO `t_form_item` VALUES ('29', '2', '全部员工(包括操作区和前台)均穿着驰加工服，并且干净，无污渍', '9', '1');
INSERT INTO `t_form_item` VALUES ('30', '2', '全部员工均佩戴工卡，无敞怀，无染发', '10', '1');
INSERT INTO `t_form_item` VALUES ('31', '2', '员工指挥车辆进出时口号洪亮，并使用手势', '11', '1');
INSERT INTO `t_form_item` VALUES ('32', '2', '任何1名施工人员日常工作时需佩戴手套', '12', '1');
INSERT INTO `t_form_item` VALUES ('33', '2', '按照规范：佩戴安全帽，护目镜，', '13', '1');
INSERT INTO `t_form_item` VALUES ('34', '2', '操作与运营', '14', '0');
INSERT INTO `t_form_item` VALUES ('35', '2', '进出工位车辆安装三件套', '15', '1');
INSERT INTO `t_form_item` VALUES ('36', '2', '使用扭力扳手（拆装螺丝）', '16', '1');
INSERT INTO `t_form_item` VALUES ('37', '2', '零件工具不落地（托盘和工具车）', '17', '1');
INSERT INTO `t_form_item` VALUES ('38', '2', '轮胎拆装清洁轮辋  ', '18', '1');
INSERT INTO `t_form_item` VALUES ('39', '2', '刹车客户：使用制动盘清洁剂清洁制动盘  ', '19', '1');
INSERT INTO `t_form_item` VALUES ('40', '2', '洗美客户检车气压', '20', '1');
INSERT INTO `t_form_item` VALUES ('41', '2', '维修客户清洁发动机舱', '21', '1');
INSERT INTO `t_form_item` VALUES ('42', '2', '车辆安全检查达到工位区车流80%', '22', '1');
INSERT INTO `t_form_item` VALUES ('43', '2', '车辆检查使用查车单，查车工具进行检查，查车单填写规范', '23', '1');
INSERT INTO `t_form_item` VALUES ('44', '2', '轮胎客户讲解6大保养，机油客户讲解有尺标示，刹车客户讲磨合，美容客户讲漆面护理知识', '24', '1');
INSERT INTO `t_form_item` VALUES ('45', '2', '晨会，夕会，日报月度规范完整', '25', '1');
INSERT INTO `t_form_item` VALUES ('46', '2', '会议记录，店长留言日志完整及时', '26', '1');
INSERT INTO `t_form_item` VALUES ('47', '2', 'Mars系统采购，结算，符合规范要求', '27', '1');
INSERT INTO `t_form_item` VALUES ('48', '2', 'Mars系统库存准确，信息完整', '28', '1');
INSERT INTO `t_form_item` VALUES ('49', '2', '店内定期进行员工培训', '29', '1');
INSERT INTO `t_form_item` VALUES ('50', '2', '体验', '30', '0');
INSERT INTO `t_form_item` VALUES ('51', '2', '收银员提供31项查车副本和Mars系统结算单，并解释清单，双程呈递', '31', '1');
INSERT INTO `t_form_item` VALUES ('52', '2', '所有顾客使用MARS结算单，实时，规范', '32', '1');
INSERT INTO `t_form_item` VALUES ('53', '2', '客户无论走到哪里，员工报以点头微笑', '33', '1');
INSERT INTO `t_form_item` VALUES ('54', '2', '车间和休息区能够适时播送驰加的背景音乐', '34', '1');
INSERT INTO `t_form_item` VALUES ('55', '2', '5秒内接车', '35', '1');
INSERT INTO `t_form_item` VALUES ('56', '2', '维修员工向顾客解释SOP亮点（包括换胎、机油更换、补胎、刹车盘、片更换）', '36', '1');
INSERT INTO `t_form_item` VALUES ('57', '2', '给等待客户递水或饮料', '37', '1');
INSERT INTO `t_form_item` VALUES ('58', '2', '所有员工不慢慢吞吞走路', '38', '1');
INSERT INTO `t_form_item` VALUES ('59', '2', '电话接听符合驰加规范要求', '39', '1');
INSERT INTO `t_form_item` VALUES ('60', '2', '当顾客离开时及时清理顾客的休息室桌面', '40', '1');
INSERT INTO `t_form_item` VALUES ('61', '4', '通知员工准备打烊，停止接待顾客，并与店内顾客沟通', '1', '1');
INSERT INTO `t_form_item` VALUES ('62', '4', '检查所有摄像探头及CCTV监控主机工作正常', '2', '1');
INSERT INTO `t_form_item` VALUES ('63', '4', '组织员工按照区域划分执行打烊工作', '3', '1');
INSERT INTO `t_form_item` VALUES ('64', '4', '完成现金日报及准备好当日存款单与值班经理确认后签字封包', '4', '1');
INSERT INTO `t_form_item` VALUES ('65', '4', '盘点收银钱箱内零找金及营业款', '5', '1');
INSERT INTO `t_form_item` VALUES ('66', '4', '按现金日报表盘点保险柜并签字确认，关闭保险柜并拨乱密码', '6', '1');
INSERT INTO `t_form_item` VALUES ('67', '4', '确认所有工单已录入DMS系统后关闭电脑系统及收银设备', '7', '1');
INSERT INTO `t_form_item` VALUES ('68', '4', '巡视检查洗车美容区，工位区的打烊清洁状况', '8', '1');
INSERT INTO `t_form_item` VALUES ('69', '4', '巡视检查接待区/员工休息室/会议室/卫生间打烊清洁情况', '9', '1');
INSERT INTO `t_form_item` VALUES ('70', '4', '巡视检查陈列货架货品是否有缺失并安排员工补齐', '10', '1');
INSERT INTO `t_form_item` VALUES ('71', '4', '召开班后总结会，回顾当日运营情况：将代办事项写入留言本', '11', '1');
INSERT INTO `t_form_item` VALUES ('72', '4', '巡视整个楼面，执行门店安全与保全检查', '12', '1');
INSERT INTO `t_form_item` VALUES ('73', '4', '关闭微电子设备后一次关闭照明设备及大功率设备（安全指示灯，招牌灯保持常亮）', '13', '1');
INSERT INTO `t_form_item` VALUES ('74', '4', '关闭所有用水设备，水龙头及总水阀', '14', '1');
INSERT INTO `t_form_item` VALUES ('75', '4', '打开门店报警系统及监控系统', '15', '1');
INSERT INTO `t_form_item` VALUES ('76', '4', '确认所有员工已经离开店铺后，锁闭所有门窗', '16', '1');

INSERT INTO `t_role` VALUES ('2', '店主');
INSERT INTO `t_role` VALUES ('3', '店长');
INSERT INTO `t_role` VALUES ('1', '顾问');